
package ma.adam.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "banqueService", targetNamespace = "http://ws.adam.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertDHToDollar", targetNamespace = "http://ws.adam.ma/", className = "ma.adam.proxy.ConvertDHToDollar")
    @ResponseWrapper(localName = "convertDHToDollarResponse", targetNamespace = "http://ws.adam.ma/", className = "ma.adam.proxy.ConvertDHToDollarResponse")
    @Action(input = "http://ws.adam.ma/banqueService/convertDHToDollarRequest", output = "http://ws.adam.ma/banqueService/convertDHToDollarResponse")
    public Double convertDHToDollar(
        @WebParam(name = "montant", targetNamespace = "")
        Double montant);

    /**
     * 
     * @return
     *     returns java.util.List<ma.adam.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://ws.adam.ma/", className = "ma.adam.proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://ws.adam.ma/", className = "ma.adam.proxy.ListComptesResponse")
    @Action(input = "http://ws.adam.ma/banqueService/listComptesRequest", output = "http://ws.adam.ma/banqueService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.adam.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompteByCode", targetNamespace = "http://ws.adam.ma/", className = "ma.adam.proxy.GetCompteByCode")
    @ResponseWrapper(localName = "getCompteByCodeResponse", targetNamespace = "http://ws.adam.ma/", className = "ma.adam.proxy.GetCompteByCodeResponse")
    @Action(input = "http://ws.adam.ma/banqueService/getCompteByCodeRequest", output = "http://ws.adam.ma/banqueService/getCompteByCodeResponse")
    public Compte getCompteByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
